apiVersion: v1
kind: Service
metadata:
  name: cons-db-srv
  namespace: messagerie
spec:
  selector:
    app: cons-db-srv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
