apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate
spec:
  replicas: 1
  selector:
    matchLabels: { app: libretranslate }
  template:
    metadata:
      labels: { app: libretranslate }
    spec:
      containers:
      - name: libretranslate
        image: libretranslate/libretranslate:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: libretranslate
  namespace: messagerie
spec:
  selector: { app: libretranslate }
  ports:
  - port: 5000
    targetPort: 5000
