apiVersion: v1
kind: Service
metadata:
  name: srv-translate
  namespace: messagerie
spec:
  selector:
    app: srv-translate
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

